//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoronaWatchDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoronaWatchDBEntities : DbContext
    {
        public CoronaWatchDBEntities()
            : base("name=CoronaWatchDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RegionDB> RegionDBs { get; set; }
        public virtual DbSet<ReportDB> ReportDBs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
