//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoronaWatchDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegionDB()
        {
            this.ReportDBs = new HashSet<ReportDB>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public string ISOCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportDB> ReportDBs { get; set; }
    }
}
