//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoronaWatchDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDB
    {
        public int Id { get; set; }
        public string ISOCode { get; set; }
        public Nullable<int> Confirmed { get; set; }
        public Nullable<int> Recovered { get; set; }
        public Nullable<int> Death { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual RegionDB RegionDB { get; set; }
    }
}
